# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setuo MSBuild
      uses: microsoft/setup-msbuild@v1.3.1
      with:
        dotnet-version: 8.0.x
    - name: Pull submodules
      run: git submodule update --init --recursive
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
